CREATE OR REPLACE PROCEDURE PROC_SP_REPEATER AS
BEGIN
  DECLARE
    CURSOR C_JOB IS
      SELECT REPEATER.INT_ID,
             RC.PROVINCE_NAME,
             RC.REGION_NAME,
             RC.CITY_NAME,
             REPEATER.COUNTY_NAME AS VILLAGE_NAME,
             REPEATER.GRID_ID GRID_NUM,
             GRID.DEP_NAME OPERATE_DEPARTMENT,
             REPEATER.REPEATER_NO,
             REPEATER.NAME AS REPEATER_NAME,
             REPEATER.COVER_AREA,
             REPEATER.COVER_TYPE,
             REPEATER.LOCATION AS ADDRESS,
             REPEATER.LONGITUDE,
             REPEATER.LATITUDE,
             REPEATER.REPEATER_TYPE SOURCE_TYPE,
             CASE
               WHEN CDMA.VENDOR_ID = 7 THEN
                CDMA.BSC_NAME
               ELSE
                GETMSCIDBYREGION(RC.REGION_NAME) || '.' || CDMA.DCSID
             END BSCID,
             CDMA.BTSID,
             CDMA.NAME AS BTS_NAME,
             CELL.CI,
             CELL.CELLID,
             CELL.PN,
             CELL.LAC,
             GETCELLWORKFREQ(GETCARRIERPOWER(283,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(201,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(242,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(160,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(37,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(78,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(119,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(1019,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID)) AS WORKFREQ,
             REPEATER.VENDOR_NAME,
             REPEATER.NEAR_REPEATER_TYPE,
             REPEATER.FAR_REPEATER_TYPE,
             REPEATER.F_GAIN,
             REPEATER.R_GAIN,
             REPEATER.POWER_MAX,
             REPEATER.POWER_ACT,
             REPEATER.ANT_TYPE ANT_MODEL,
             REPEATER.HEIGHT,
             REPEATER.DIR,
             REPEATER.DOWNTILT,
             REPEATER.DECORATIVE_ANTENNA,
             REPEATER.USE_TIME,
             REPEATER.STATUS SYSTEM_STATUS,
             REPEATER.MONITOR,
             REPEATER.DISTANCE,
             REPEATER.FDD_LENGTH,
             REPEATER.ANTENNA_FEEDER_AUTHORITY,
             REPEATER.SOURCE_SIGNAL_AREA,
             REPEATER.MAINTAIN_PERSON,
             REPEATER.MAINTENANCE_PERSON_PHONE,
             REPEATER.CONTACT_OWNER,
             REPEATER.CONTACT_OWNER_PHONE,
             REPEATER.UPDATE_TIME OPERATIONTIME,
             C.DISPLAY_NAME AS OPERATIONUSERNAME,
             REPEATER.REMARK,
             REPEATER.REGION_ID,
             REPEATER.CITY_ID
        FROM C_TCO_PRO_REPEATER REPEATER
        LEFT JOIN CDMAUSER.C_CELL CELL
          ON REPEATER.RELATED_CELL = CELL.INT_ID
        LEFT JOIN CDMAUSER.C_BTS CDMA
          ON CELL.RELATED_BTS = CDMA.INT_ID
        LEFT JOIN C_TCO_PRO_BTS BTS
          ON CELL.RELATED_BTS = BTS.INT_ID
        LEFT JOIN C_REGION_CITY RC
          ON RC.CITY_ID = REPEATER.CITY_ID
        LEFT JOIN C_TCO_USER_V2 C
          ON REPEATER.OPERATIONUSERID = C.USER_ID
        LEFT JOIN TCO_PRO_GRID GRID
          ON REPEATER.GRID_ID = GRID.GRID_NO;
    --定义一个游标变量v_cinfo c_emp%ROWTYPE ，该类型为游标c_emp中的一行数据类型
    C_ROW C_JOB%ROWTYPE;
  BEGIN
    FOR C_ROW IN C_JOB LOOP
      BEGIN
        INSERT INTO HD_C_PRO_REPEATER
          (INT_ID,
           PROVINCE_NAME,
           REGION_NAME,
           CITY_NAME,
           VILLAGE_NAME,
           GRID_NUM,
           OPERATE_DEPARTMENT,
           REPEATER_NO,
           REPEATER_NAME,
           COVER_AREA,
           COVER_TYPE,
           ADDRESS,
           LONGITUDE,
           LATITUDE,
           SOURCE_TYPE,
           BSCID,
           BTSID,
           BTS_NAME,
           CI,
           CELLID,
           PN,
           LAC,
           WORKFREQ,
           VENDOR_NAME,
           NEAR_REPEATER_TYPE,
           FAR_REPEATER_TYPE,
           F_GAIN,
           R_GAIN,
           POWER_MAX,
           POWER_ACT,
           ANT_MODEL,
           HEIGHT,
           DIR,
           DOWNTILT,
           DECORATIVE_ANTENNA,
           USE_TIME,
           SYSTEM_STATUS,
           MONITOR,
           DISTANCE,
           FDD_LENGTH,
           ANTENNA_FEEDER_AUTHORITY,
           SOURCE_SIGNAL_AREA,
           MAINTAIN_PERSON,
           MAINTENANCE_PERSON_PHONE,
           CONTACT_OWNER,
           CONTACT_OWNER_PHONE,
           OPERATIONTIME,
           OPERATIONUSERNAME,
           REMARK,
           REGION_ID,
           CITY_ID,
           HD_TIME)
        VALUES
          (C_ROW.INT_ID,
           C_ROW.PROVINCE_NAME,
           C_ROW.REGION_NAME,
           C_ROW.CITY_NAME,
           C_ROW.VILLAGE_NAME,
           C_ROW.GRID_NUM,
           C_ROW.OPERATE_DEPARTMENT,
           C_ROW.REPEATER_NO,
           C_ROW.REPEATER_NAME,
           C_ROW.COVER_AREA,
           C_ROW.COVER_TYPE,
           C_ROW.ADDRESS,
           C_ROW.LONGITUDE,
           C_ROW.LATITUDE,
           C_ROW.SOURCE_TYPE,
           C_ROW.BSCID,
           C_ROW.BTSID,
           C_ROW.BTS_NAME,
           C_ROW.CI,
           C_ROW.CELLID,
           C_ROW.PN,
           C_ROW.LAC,
           C_ROW.WORKFREQ,
           C_ROW.VENDOR_NAME,
           C_ROW.NEAR_REPEATER_TYPE,
           C_ROW.FAR_REPEATER_TYPE,
           C_ROW.F_GAIN,
           C_ROW.R_GAIN,
           C_ROW.POWER_MAX,
           C_ROW.POWER_ACT,
           C_ROW.ANT_MODEL,
           C_ROW.HEIGHT,
           C_ROW.DIR,
           C_ROW.DOWNTILT,
           C_ROW.DECORATIVE_ANTENNA,
           C_ROW.USE_TIME,
           C_ROW.SYSTEM_STATUS,
           C_ROW.MONITOR,
           C_ROW.DISTANCE,
           C_ROW.FDD_LENGTH,
           C_ROW.ANTENNA_FEEDER_AUTHORITY,
           C_ROW.SOURCE_SIGNAL_AREA,
           C_ROW.MAINTAIN_PERSON,
           C_ROW.MAINTENANCE_PERSON_PHONE,
           C_ROW.CONTACT_OWNER,
           C_ROW.CONTACT_OWNER_PHONE,
           C_ROW.OPERATIONTIME,
           C_ROW.OPERATIONUSERNAME,
           C_ROW.REMARK,
           C_ROW.REGION_ID,
           C_ROW.CITY_ID,
           SYSDATE);
        COMMIT;
      END;
    END LOOP;
  END;
END PROC_SP_REPEATER;
