CREATE OR REPLACE PROCEDURE PROC_GET_OPTIMIZEWORK_CODE --用于生成作业计划、工单的CODE 安徽版本
(REGION_ID    IN NUMBER,
 CODE_TYPE    IN NUMBER, --1 作业计划，2 工单,3 为在线问题类型,4 规划站类型
 RETURNSTRING OUT VARCHAR2) IS
  V_SERIALNUM   NUMBER := 0; --序号
  V_STRPART     VARCHAR2(20) := '';
  V_PROVINCE_ID NUMBER := 0;
  V_REGION_ID   NUMBER := 0;
  --v_lock     number :=0;
BEGIN
  V_REGION_ID := REGION_ID;
  SELECT MIN(PROVINCE_ID) INTO V_PROVINCE_ID FROM C_REGION_CITY;

  IF REGION_ID = V_PROVINCE_ID THEN
    V_REGION_ID := -1;
  END IF;

  --select * from TAP_WORKPLAN_CODESERIAL for update; --modify by maojun;锁住表

  SELECT NVL(MAX(SERIALNUM), 0)
    INTO V_SERIALNUM
    FROM TAP_WORKPLAN_CODESERIAL
   WHERE REGIONID = V_REGION_ID
     AND CODETYPE = CODE_TYPE
     AND CODEDATE = TRUNC(SYSDATE);

  SELECT TO_CHAR(SYSDATE, 'yyyyMMdd') || LPAD(B.NUM, 3, 0) || PAC
    INTO V_STRPART
    FROM DUAL A,
         (SELECT NVL(MAX(SERIALNUM), 0) + 1 NUM
            FROM TAP_WORKPLAN_CODESERIAL
           WHERE REGIONID = V_REGION_ID
             AND CODETYPE = CODE_TYPE
             AND CODEDATE = TRUNC(SYSDATE)) B,
         (SELECT MAX(REGION_PAC) PAC
            FROM C_REGION_CITY
           WHERE REGION_ID = V_REGION_ID) C;

  IF V_SERIALNUM = 0 THEN
    BEGIN
      INSERT INTO TAP_WORKPLAN_CODESERIAL
      VALUES
        (TRUNC(SYSDATE), V_REGION_ID, 1, CODE_TYPE);
      COMMIT;
    END;
  ELSE
    BEGIN
      UPDATE TAP_WORKPLAN_CODESERIAL
         SET SERIALNUM = SERIALNUM + 1
       WHERE REGIONID = V_REGION_ID
         AND CODEDATE = TRUNC(SYSDATE)
         AND CODETYPE = CODE_TYPE;
      COMMIT;
    END;
  END IF;

  COMMIT;

  IF CODE_TYPE = 1 THEN
    RETURNSTRING := 'P' || V_STRPART; --作业计划
  ELSIF CODE_TYPE = 2 THEN
    RETURNSTRING := 'W' || V_STRPART; --工单
  ELSIF CODE_TYPE = 3 THEN
    RETURNSTRING := 'I' || V_STRPART; --在线问题
  ELSIF CODE_TYPE = 4 THEN
    RETURNSTRING := 'PB' || V_STRPART; --规划站
  END IF;
END;
