CREATE OR REPLACE PROCEDURE PROC_TY_ALARM_SYNC IS
--v_sql varchar(3000);
BEGIN
 EXECUTE IMMEDIATE 'TRUNCATE TABLE TY_NE_ZFZ';
 COMMIT;
 EXECUTE IMMEDIATE 'INSERT INTO TY_NE_ZFZ SELECT * FROM  NMSDB.NE_ZFZ@TYDB';
 COMMIT;
 EXECUTE IMMEDIATE 'TRUNCATE TABLE TY_ALARMINFO';
 COMMIT;
 EXECUTE IMMEDIATE 'INSERT INTO TY_ALARMINFO SELECT * FROM  NMSDB.V_BOCO_ALARMINFO@TYDB';
 COMMIT;
 EXECUTE IMMEDIATE 'TRUNCATE TABLE TY_ALARMHISTORY';
 COMMIT;
 EXECUTE IMMEDIATE 'INSERT INTO TY_ALARMHISTORY SELECT * FROM  NMSDB.V_BOCO_ALARMHISTORY@TYDB WHERE STARTTIME > SYSDATE -30';
 COMMIT;
END PROC_TY_ALARM_SYNC;
