CREATE OR REPLACE PROCEDURE PROC_SP_INDOORS AS
BEGIN
  DECLARE
    CURSOR C_JOB IS
      SELECT INDOORS.INT_ID,
             RC.PROVINCE_NAME,
             RC.REGION_NAME,
             RC.CITY_NAME,
             INDOORS.COUNTY_NAME AS VILLAGE_NAME,
             INDOORS.GRID_ID GRID_NUM,
             GRID.DEP_NAME OPERATE_DEPARTMENT,
             INDOORS.INDDS_CODE INDOORS_NO,
             INDOORS.NAME AS INDOORS_NAME,
             INDOORS.COVER_DISTR_SYSTEM,
             INDOORS.BUILDING_TYPE,
             INDOORS.COVER_EARE COVER_AREA,
             INDOORS.LOCATION AS ADDRESS,
             INDOORS.LONGITUDE,
             INDOORS.LATITUDE,
             INDOORS.INFO_RESOURCE SOURCE_TYPE,
             INDOORS.BUILDING_NUM,
             INDOORS.BUILDING_FLOOR,
             INDOORS.BUILDING_AREA,
             INDOORS.INDOOR_BUILDING_NUM,
             INDOORS.INDOOR_BUILDING_FLOOR,
             INDOORS.INDOOR_BUILDING_AREA,
             INDOORS.OUTDOOR_BUILDING_NUM,
             CASE
               WHEN CDMA.VENDOR_ID = 7 THEN
                CDMA.BSC_NAME
               ELSE
                GETMSCIDBYREGION(RC.REGION_NAME) || '.' || CDMA.DCSID
             END BSCID,
             CDMA.BTSID,
             CDMA.NAME AS BTS_NAME,
             INDOORS.CI,
             CELL.CELLID,
             CELL.PN,
             CELL.LAC,
             GETCELLWORKFREQ(GETCARRIERPOWER(283,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(201,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(242,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(160,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(37,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(78,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(119,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID),
                             GETCARRIERPOWER(1019,
                                             TO_CHAR(CELL.INT_ID),
                                             CELL.VENDOR_ID)) AS WORKFREQ,
             INDOORS.VENDOR_NAME,
             INDOORS.NEAR_REPEATER_NUM,
             INDOORS.FAR_REPEATER_NUM,
             INDOORS.INTEGRATOR,
             INDOORS.APPLIANCE_PROVIDE_VENDOR,
             INDOORS.AMPLIFIER_NBR,
             INDOORS.COUPLER_POWER_DIVIDER_NUM,
             INDOORS.ATTENUATOR_NUM,
             INDOORS.OPEN_TIME ONLINE_DATE,
             INDOORS.INDOORS_CLASS,
             INDOORS.SYS_STATUS,
             INDOORS.MONITOR,
             INDOORS.DISTANCE,
             INDOORS.FDD_LENGTH FIBERLENGTH,
             INDOORS.ANTENNA_FEEDER_AUTHORITY,
             INDOORS.COMBINING_MODE,
             CASE
               WHEN INDOORS.COMBINING_MODE = 'C网专用' THEN
                '否'
               ELSE
                '是'
             END AS COMBINING,
             INDOORS.MAINTENANCE_UNIT MAINTAIN_PERSON,
             INDOORS.MAINTENANCE_PERSON_PHONE,
             INDOORS.CONTACT_OWNER,
             INDOORS.CONTACT_OWNER_PHONE,
             INDOORS.UPDATE_TIME OPERATIONTIME,
             C.DISPLAY_NAME AS OPERATIONUSERNAME,
             INDOORS.NOTE REMARK,
             INDOORS.REGION_ID,
             INDOORS.CITY_ID
        FROM C_TCO_PRO_INDOORS INDOORS
        LEFT JOIN C_REGION_CITY RC
          ON RC.CITY_ID = INDOORS.CITY_ID
        LEFT JOIN C_TCO_USER_V2 C
          ON INDOORS.OPERATIONUSERID = C.USER_ID
        LEFT JOIN CDMAUSER.C_CELL CELL
          ON INDOORS.RELATED_CELL = CELL.INT_ID
        LEFT JOIN CDMAUSER.C_BTS CDMA
          ON CELL.RELATED_BTS = CDMA.INT_ID
        LEFT JOIN C_TCO_PRO_BTS BTS
          ON CELL.RELATED_BTS = BTS.INT_ID
        LEFT JOIN TCO_PRO_GRID GRID
          ON INDOORS.GRID_ID = GRID.GRID_NO;

    --定义一个游标变量v_cinfo c_emp%ROWTYPE ，该类型为游标c_emp中的一行数据类型
    C_ROW C_JOB%ROWTYPE;
  BEGIN
    FOR C_ROW IN C_JOB LOOP
      BEGIN
        INSERT INTO HD_C_PRO_INDOORS
          (INT_ID,
           PROVINCE_NAME,
           REGION_NAME,
           CITY_NAME,
           VILLAGE_NAME,
           GRID_NUM,
           OPERATE_DEPARTMENT,
           INDOORS_NO,
           INDOORS_NAME,
           COVER_DISTR_SYSTEM,
           BUILDING_TYPE,
           COVER_AREA,
           ADDRESS,
           LONGITUDE,
           LATITUDE,
           SOURCE_TYPE,
           BUILDING_NUM,
           BUILDING_FLOOR,
           BUILDING_AREA,
           INDOOR_BUILDING_NUM,
           INDOOR_BUILDING_FLOOR,
           INDOOR_BUILDING_AREA,
           OUTDOOR_BUILDING_NUM,
           BSCID,
           BTSID,
           BTS_NAME,
           CI,
           CELLID,
           PN,
           LAC,
           WORKFREQ,
           VENDOR_NAME,
           NEAR_REPEATER_NUM,
           FAR_REPEATER_NUM,
           INTEGRATOR,
           APPLIANCE_PROVIDE_VENDOR,
           AMPLIFIER_NBR,
           COUPLER_POWER_DIVIDER_NUM,
           ATTENUATOR_NUM,
           ONLINE_DATE,
           INDOORS_CLASS,
           SYS_STATUS,
           MONITOR,
           DISTANCE,
           FIBERLENGTH,
           ANTENNA_FEEDER_AUTHORITY,
           COMBINING_MODE,
           COMBINING,
           MAINTAIN_PERSON,
           MAINTENANCE_PERSON_PHONE,
           CONTACT_OWNER,
           CONTACT_OWNER_PHONE,
           OPERATIONTIME,
           OPERATIONUSERNAME,
           REMARK,
           REGION_ID,
           CITY_ID,
           HD_TIME)
        VALUES
          (C_ROW.INT_ID,
           C_ROW.PROVINCE_NAME,
           C_ROW.REGION_NAME,
           C_ROW.CITY_NAME,
           C_ROW.VILLAGE_NAME,
           C_ROW.GRID_NUM,
           C_ROW.OPERATE_DEPARTMENT,
           C_ROW.INDOORS_NO,
           C_ROW.INDOORS_NAME,
           C_ROW.COVER_DISTR_SYSTEM,
           C_ROW.BUILDING_TYPE,
           C_ROW.COVER_AREA,
           C_ROW.ADDRESS,
           C_ROW.LONGITUDE,
           C_ROW.LATITUDE,
           C_ROW.SOURCE_TYPE,
           C_ROW.BUILDING_NUM,
           C_ROW.BUILDING_FLOOR,
           C_ROW.BUILDING_AREA,
           C_ROW.INDOOR_BUILDING_NUM,
           C_ROW.INDOOR_BUILDING_FLOOR,
           C_ROW.INDOOR_BUILDING_AREA,
           C_ROW.OUTDOOR_BUILDING_NUM,
           C_ROW.BSCID,
           C_ROW.BTSID,
           C_ROW.BTS_NAME,
           C_ROW.CI,
           C_ROW.CELLID,
           C_ROW.PN,
           C_ROW.LAC,
           C_ROW.WORKFREQ,
           C_ROW.VENDOR_NAME,
           C_ROW.NEAR_REPEATER_NUM,
           C_ROW.FAR_REPEATER_NUM,
           C_ROW.INTEGRATOR,
           C_ROW.APPLIANCE_PROVIDE_VENDOR,
           C_ROW.AMPLIFIER_NBR,
           C_ROW.COUPLER_POWER_DIVIDER_NUM,
           C_ROW.ATTENUATOR_NUM,
           C_ROW.ONLINE_DATE,
           C_ROW.INDOORS_CLASS,
           C_ROW.SYS_STATUS,
           C_ROW.MONITOR,
           C_ROW.DISTANCE,
           C_ROW.FIBERLENGTH,
           C_ROW.ANTENNA_FEEDER_AUTHORITY,
           C_ROW.COMBINING_MODE,
           C_ROW.COMBINING,
           C_ROW.MAINTAIN_PERSON,
           C_ROW.MAINTENANCE_PERSON_PHONE,
           C_ROW.CONTACT_OWNER,
           C_ROW.CONTACT_OWNER_PHONE,
           C_ROW.OPERATIONTIME,
           C_ROW.OPERATIONUSERNAME,
           C_ROW.REMARK,
           C_ROW.REGION_ID,
           C_ROW.CITY_ID,
           SYSDATE);
        COMMIT;
      END;
    END LOOP;
  END;
END PROC_SP_INDOORS;
