CREATE OR REPLACE FUNCTION GETBTSANTTYPE(INTID LONG) RETURN VARCHAR2 IS
  RESULT VARCHAR2(32);
BEGIN
  RESULT := NULL;

  SELECT CASE
           WHEN ANTENNA.ANTENNA_DIRECTION = 1 THEN
            '全向'
           WHEN ANTENNA.ANTENNA_DIRECTION = 2 THEN
            '定向'
           WHEN ANTENNA.ANTENNA_DIRECTION = 3 THEN
            '室分天线'
           ELSE
            TO_CHAR(ANTENNA.ANTENNA_DIRECTION)
         END ANTTYPE
    INTO RESULT
    FROM C_TCO_PRO_CELL A
    LEFT JOIN C_TCO_PRO_ANTENNA ANTENNA
      ON (A.ANT_VENDOR = ANTENNA.MANUFA_NAME AND
         A.ANT_MODEL = ANTENNA.ANTENNA_TYPE)
   WHERE A.RELATED_BTSID = INTID
     AND (POWER_DIVIDERS_CELL_ID = 0 OR POWER_DIVIDERS_CELL_ID is NULL)  --非功分扇区
     AND ROWNUM = 1;
  IF RESULT IS NULL THEN
    RETURN('');
  ELSE
    RETURN(RESULT);
  END IF;
END GETBTSANTTYPE;
