CREATE OR REPLACE FUNCTION GETRADIUSBYCOVER(RESOURCETYPE VARCHAR2,
                                                  CHECKTYPE    VARCHAR2)
  RETURN NUMBER IS
  RESULT NUMBER;
BEGIN
  IF RESOURCETYPE = 'Cell' THEN
    IF CHECKTYPE = '市区' OR CHECKTYPE = '县城' THEN
      RETURN(250);
    ELSIF CHECKTYPE = '郊区' THEN
      RETURN(500);
    ELSE
      RETURN(2000);
    END IF;
  ELSIF RESOURCETYPE = 'IndoorDistribute' THEN
    IF CHECKTYPE = '室内' THEN
      RETURN(50);
    ELSE
      RETURN(200);
    END IF;
  ELSIF RESOURCETYPE = 'Repeater' THEN
    IF CHECKTYPE = '市区' OR CHECKTYPE = '县城' THEN
      RETURN(250);
    ELSIF CHECKTYPE = '郊区' THEN
      RETURN(500);
    ELSE
      RETURN(2000);
    END IF;
  ELSIF RESOURCETYPE = 'SurBts' THEN
    IF CHECKTYPE = '市区' OR CHECKTYPE = '县城' THEN
      RETURN(250);
    ELSIF CHECKTYPE = '郊区' THEN
      RETURN(500);
    ELSE
      RETURN(2000);
    END IF;
  ELSIF RESOURCETYPE = 'SurIndoors' THEN
    IF CHECKTYPE = '室内' THEN
      RETURN(50);
    ELSE
      RETURN(200);
    END IF;
  END IF;
  RETURN(RESULT);
END GETRADIUSBYCOVER;
